### ISSUE TITLE
How to adjust params for matching ?

### ISSUE THREAD

**Issue by killzoner** [rust-cv/akaze#3]
Hi there,

Disclaimer: i'm completely new to computer vision, please forgive me for the maybe silly questions

I was trying to use feature matching with rust, and i came accross your crate `rust-cv` and the one from `indianajohn`. I had pretty good starts with the second one matching images, but yours is really much faster at computation.

However, i don't have much the results from matching i had with the other crate. I'm pretty sure it's due to the params I used, or the nature of the images. I tried running https://github.com/rust-cv/akaze/blob/master/tests/estimate_pose.rs on my sample images but it fails estimating the model.

Can you give a clue about what I can do to evaluate the model / calibrate things, or if it's really too complicated for beginners, some good resources to learn what is necessary for that ?

Thanks in advance, and bravo for making these kind of work entering the rust space

**Comment by vadixidav** [comment]
@killzoner You are likely running into the fact that the example provided uses a sparse keypoint detection to make the test perform quickly. It stems from this line: `akaze::Config::sparse()`. You can change this to one of the other configurations specified in the documentation. To get similar results to the original akaze crate, use `Config::default()`. The results might be slightly better due to a change in the way images are downsampled in the image pyramid and a small bugfix in the diffusion code, but aside from that there should be little difference.

The parameter that affects matching the most is the response threshold. If you want to change it to a specific number you can use `Config::new(0.001)` and modify the number. Lower thresholds produce more points and higher thresholds produce less points. Typically you shouldn't decrease it to be less than `0.01` or you likely wont get enough points for matching.

Let me know if this worked for you and we can close the issue. Thanks for trying out the crate and filing this issue! Activity is good to see.

**Comment by vadixidav** [comment]
Also the performance improvement when comparing just feature extraction 1 to 1 should be about 3x faster when compiled with native processor extensions, but the overall execution will potentially be faster/more accurate than this due to the use of the arrsac and eight-point crates, so I would not compare both akaze on the basis of the test example since the results would be based on not just akaze.

**Comment by vadixidav** [comment]
For calibration you just need to get the focal length in pixels and the optical center in pixels. At the very least you can just put in the focal length in pixels and estimate the optical center. You should still get matching happening, but it won't be as robust/perfect. You can print out a checkerboard pattern and use existing camera calibration tools to get these values. For the focal length in pixels, you need to get the focal length (which can be complicated sometimes), the dimensions of your sensor, and the dimensions of your image. You then mutiply the width in pixels by the focal length divided by the width and you will get focal length in pixels. That should be enough to get you going.

Rust CV is currently working on calibration tools, so hopefully we will have those soon.

**Comment by killzoner** [comment]
Hi @vadixidav , thank you so much lot for your quick response ! 

Had not the time to go really far right now, but the tip with `Config::default()` did the trick, at least now i'm getting "similar" results in term of pertinence. Playing with `LOWES_RATIO` also helped, and now i can get a model from my sample images (not sure yet what i can do with though)

I will try the calibration thing this week end when i get some time. Looking forward to give you feedback on the tools you're working on when it's ready.

For the record, on my tiny sample data (10 images), the matching goes from ~10s to ~1s, so it's huge improvement for "similar" results

**Comment by vadixidav** [comment]
@killzoner That is a huge preformance increase! I recommend that you join the Rust CV Discord if you need further help with calibration as we have a lot of experienced individuals in there that would love to help.

**Comment by killzoner** [comment]
sure, appreciate it

**Comment by killzoner** [comment]
Mmh i tried running into the calibration thing, but re-reading your comment it appears that it would not really be relevant in my case. 

In fact i'm working on totally random photos taken from the web, so i have multiple blockers for calibrating : i don't know the sensor and the images have different dimensions each of them. 

Well i'm pretty amazed it's working though, I got 3 out of 4 images matching their siblings, the remaining ones having really bad quality (artifacts, distortion, etc.) so it's no surprise this one has trouble being matched. Great work!

**Comment by vadixidav** [comment]
@killzoner What you want is for there to be a view graph and graph optimization performed on it, including the camera intrinsics for each image. This process is typically called SfM. That is something we are planning to work on, but right now we assume that the camera has been calibrated in advance just to make things easier. It is possible to get reconstructions out even with bad calibration parameters though, but as you have found out they have massive distortion.

You can keep up with our progress on the Discord server if you are interested in us developing more SfM capabilities. I am glad to see that you got some use out of it!
